import { Verification_Email_Template, Welcome_Email_Template, Reset_Password_Email_Template, Password_Change_Success_Template, Reset_Password_OTP_Template } from "./EmailTemplate.js";
import { resend, transporter } from "./Email.config.js";
import { dashboardUrl } from "../consts.js";
//  console.log(transporter);

export const sendVerificationEmail = async (email, name, verificationCode) => {
  try {
    const response = await resend.emails.send({
      from: `AISA <${process.env.EMAIL}>`,
      to: [email],
      subject: "Verify Your Email",
      html: Verification_Email_Template.replace("{name}", name).replace("{verificationCode}", verificationCode)
    })
    console.log("resend_msg", response);

  } catch (error) {
    console.log('Email error', error)
  }
}

// WELCOME EMAIL
export const welcomeEmail = async (name, email) => {
  const info = await resend.emails.send({
    from: `AISA <${process.env.EMAIL}>`,
    to: [email],
    subject: `Welcome ${name}`,
    html: Welcome_Email_Template.replace("{name}", name).replace("{dashboardUrl}", dashboardUrl),
  });

};

export const sendResetPasswordEmail = async (email, name, resetUrl) => {
  try {
    const response = await resend.emails.send({
      from: `AISA <${process.env.EMAIL}>`,
      to: [email],
      subject: "Reset Your Password",
      html: Reset_Password_Email_Template.replace("{name}", name).replace("{resetUrl}", resetUrl)
    })
    console.log("resend_msg", response);
  } catch (error) {
    console.log('Email error', error)
  }
}

export const sendResetPasswordOTP = async (email, name, otpCode) => {
  try {
    const response = await resend.emails.send({
      from: `AISA <${process.env.EMAIL}>`,
      to: [email],
      subject: "Your Password Reset OTP",
      html: Reset_Password_OTP_Template.replace("{name}", name).replace("{otpCode}", otpCode)
    })
    console.log("resend_otp_msg", response);
  } catch (error) {
    console.log('Email OTP error', error)
  }
}

export const sendPasswordChangeSuccessEmail = async (email, name) => {
  try {
    const response = await resend.emails.send({
      from: `AISA <${process.env.EMAIL}>`,
      to: [email],
      subject: "Password Updated Successfully",
      html: Password_Change_Success_Template.replace("{name}", name)
    })
    console.log("resend_msg", response);
  } catch (error) {
    console.log('Email error', error)
  }
}

export const sendFeedbackEmail = async (feedback) => {
  try {
    const isUp = feedback.type === 'thumbs_up';
    const response = await resend.emails.send({
      from: `AISA Feedback <${process.env.EMAIL}>`,
      to: ['admin@uwo24.com'],
      subject: `📢 New Feedback: ${isUp ? 'Positive' : 'Negative'}`,
      html: `
        <div style="font-family: sans-serif; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
          <h2 style="color: ${isUp ? '#10b981' : '#ef4444'}">${isUp ? '👍 Thumbs Up' : '👎 Thumbs Down'}</h2>
          <p><strong>Session ID:</strong> ${feedback.sessionId}</p>
          <p><strong>Message ID:</strong> ${feedback.messageId}</p>
          ${feedback.categories && feedback.categories.length > 0 ? `<p><strong>Categories:</strong> ${feedback.categories.join(', ')}</p>` : ''}
          <p><strong>Details:</strong> ${feedback.details || 'None'}</p>
          <hr />
          <p style="font-size: 12px; color: #666;">Generated by AISA Feedback System</p>
        </div>
      `
    });
    console.log("feedback_email_res", response);
  } catch (error) {
    console.log('Feedback email error', error);
  }
}


