runtime: nodejs20
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10

env_variables:
  NODE_ENV: 'production'
  # The PORT environment variable is automatically set by App Engine to 8080,
  # but defining it here explicitly can be helpful for local testing with dev_appserver.py.
  PORT: '8080'
  
  # -------------------------------------------------------------
  # IMPORTANT: Update these values before deploying!
  # Or use Secret Manager for sensitive keys
  # -------------------------------------------------------------
  GCP_PROJECT_ID: 'ai-mall-484810'
  MONGODB_ATLAS_URI: 'YOUR_MONGODB_CONNECTION_STRING_HERE'
  GEMINI_API_KEY: 'YOUR_GEMINI_API_KEY_HERE'
  RAZORPAY_KEY_ID: 'YOUR_RAZORPAY_KEY_ID'
  RAZORPAY_KEY_SECRET: 'YOUR_RAZORPAY_SECRET'
